<a href="https://colab.research.google.com/github/sammanfatima/Numpy-by-me/blob/main/Mastering_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Introduction**


* Numpy is used to store and process large amount of numerical data(num, arrays, pixels, matrices) efficiently



In [1]:
# install by running by this code
pip install numpy

In [4]:
import numpy as np
print(np.__version__)

2.1.3


# What is an array?

*   An array is simply a collection of multiple values stored together.
*   Data structure in programming
*   NumPy array: stores numerical values together and lets you perform          mathematical operations on them efficiently.



In [5]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [11]:
a = np.arange(6)
print(a)
a.shape # only 6 col

[0 1 2 3 4 5]


(6,)

#2D array

In [16]:
a2 = a[:, np.newaxis]
print(a2)
a2.shape # 6 rows 1 col 2d arr


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [17]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape # 6 col 1 row

[[0 1 2 3 4 5]]


(1, 6)

#3D array

In [18]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape # 1 block 1 row 6 val; block-> 3 levels of brackets
# axis 0 has size 1, axis 1 has size 1, axix 2 has size 6

[[[0 1 2 3 4 5]]]


(1, 1, 6)

# why do we have 1d, 2d, 3d arrays and where we need in data science and ml?

We use different dimensions because different types of data have different structures. For a simple list, we use 1D. For rows and columns like a table, we use 2D. For data with an additional level, we use 3D or more. This helps us organize data properly and allows ML models and other programs to process the data correctly

* **1D array** → A simple list of values. Example: [10, 20, 30, 40]. Used for one type of data, like marks, ages, or a list of numbers.
* **2D array **→ Data arranged in rows and columns, like a table. Example: [[10, 20], [30, 40]]. Very common in Data Science and ML for datasets.
* **3D array** → Data arranged in multiple tables/blocks. Commonly used for images (height × width × color channels) and some ML data.
* **Why do we need different dimensions?** → Because real-world data has different structures. A simple list needs 1D, a table needs 2D, and more complex data like images or batches may need 3D+.
* **In ML:** NumPy arrays help us store, organize, and perform calculations on numerical data before giving that data to ML models.

# Creating arrays with numpy

In [20]:
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [28]:
a.dtype # data type of arrays elements

dtype('int64')

In [34]:
type(a) # type of array

numpy.ndarray

In [23]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(b)
b.shape # 2d 2 rows 5 cols

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

# Initialize arrays

In [25]:
zeros = np.zeros((3,4)) # 3 rows 4 cols
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
zeros.dtype

dtype('float64')

In [26]:
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
full = np.full((2,5), 5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [31]:
full.dtype

dtype('int64')

In [32]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
identity.dtype

dtype('float64')

# Array attributes

In [35]:
a.shape # shape of array

(5,)

In [36]:
len(a) # no of elements in array

5

In [37]:
a.ndim # dimension of array

1

In [38]:
identity.ndim

2

In [39]:
a.size

5

# Basic operation

In [40]:
g = a - b # subtration
g

array([[ 0,  0,  0,  0,  0],
       [-5, -5, -5, -5, -5]])

In [41]:
g = b - a
g

array([[0, 0, 0, 0, 0],
       [5, 5, 5, 5, 5]])

In [42]:
s = a + b
s

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [44]:
s1 = np.add(a,b)
s1

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [46]:
s = a * b
s

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50]])

In [47]:
s = a / b
s

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]])

In [48]:
s = a**2
s

array([ 1,  4,  9, 16, 25])