<a href="https://colab.research.google.com/github/sammanfatima/Numpy-by-me/blob/main/Mastering_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Part 2

In [1]:
import numpy as np

# Empty array

In [2]:
empty = np.empty((2, 3))
print(empty)

[[1.30573645e-318 0.00000000e+000 6.87525183e-310]
 [5.34393766e-315 6.87525196e-310 3.05627255e-312]]


In [3]:
empty = np.empty((2))
print(empty)

[4.94065646e-324 6.87526938e-310]


In [4]:
empty = np.empty((2))
print(empty)
print(empty[0])

[4.94065646e-324 6.87526938e-310]
5e-324


In [5]:
empty = np.empty((2, 4))
print(empty)
print(empty[1])

[[5.36623692e-315 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[0. 0. 0. 0.]


In [6]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [7]:
x = np.arange(60)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

# Array of even numbers

In [8]:
even = np.arange(0, 23, 2) # start from 0 , stop before 23 , gap/step 2
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

# Array of odd numbers

In [9]:
odd = np.arange(0, 23, 2)
odd

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

# Specific difference between numbers

In [10]:
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

# Linspace

In [11]:
# it follow linear trend means something changes at even rate
lin = np.linspace(0, 20, num=10) # 10 is the number of elements
lin


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [12]:
lin = np.linspace(0, 10, num=5) # 5 is the number of elements
lin


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
lin.dtype

dtype('float64')

# Arrangement of Arrays

In [14]:
# sorting
arr = np.array([2, 5, 8, 7, 6, 3, 10, 4, 1, 9])
arr

array([ 2,  5,  8,  7,  6,  3, 10,  4,  1,  9])

In [15]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenation

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

# Concatenate 2d arrays

In [17]:
a = np.array([[1, 2], [3, 4]]) # 2 x 2 matrix
b = np.array([[5, 6]]) # 1 x 2
c = np.concatenate((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a.size

4

In [19]:
len(a)

2

In [20]:
s = np.array = ([[5, 1], [7,8]])


In [21]:
s1 = np.concatenate((a, s), axis=1)
s1

array([[1, 2, 5, 1],
       [3, 4, 7, 8]])

#3d arrays

For 3d arrays we have 3 double dimensions

In [22]:
import numpy as np
arr = np.array([
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],

    [[0, 1, 2, 3],
     [4, 5, 6, 7]],

    [[0, 1, 2, 3],
     [4, 5, 6, 7]]
])

In [24]:
arr.size


24

In [25]:
len(arr)

3

In [26]:
arr.ndim

3

In [27]:
arr.shape

(3, 2, 4)

# Indexing and slicing

In [28]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
a[2]


np.int64(3)

In [31]:
a[2:]

array([3, 4, 5, 6, 7])

In [32]:
a[2:5]

array([3, 4, 5])

In [33]:
a[-4:]

array([4, 5, 6, 7])

In [34]:
a[-4:-2]

array([4, 5])

In [35]:
a[1:] # left side from right side to

array([2, 3, 4, 5, 6, 7])

In [36]:
a[a<5]

array([1, 2, 3, 4])

In [37]:
a[a > 6]

array([7])